[package]
name = "git-tui"
version = "0.0.0"
repository = "https://github.com/Byron/git-oxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dedicated to a terminal user interface to interact with git repositories"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"

[[bin]]
name = "gixi"
path = "src/main.rs"
doctest = false
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
