[package]
name = "git-pathspec"
version = "0.0.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dealing magical pathspecs"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-glob = { version = "^0.3.0", path = "../git-glob" }
git-attributes = { version = "^0.1.0", path = "../git-attributes" }

bstr = { version = "0.2.13", default-features = false, features = ["std"]}
bitflags = "1.3.2"
thiserror = "1.0.26"
compact_str = "0.3.2"

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
once_cell = "1.12.0"
