[package]
name = "gix-quote"
version = "0.4.7"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing with various quotations used by git"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
bstr = { version = "1.3.0", default-features = false, features = ["std"]}
thiserror = "1.0.38"
btoi = "0.4.2"
