[package]
name = "gix-actor"
version = "0.31.5"
description = "A way to identify git actors"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"

[lib]
doctest = false


[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-date/serde"]

[dependencies]
gix-date = { version = "^0.8.7", path = "../gix-date" }
gix-utils = { version = "^0.1.11", path = "../gix-utils" }

thiserror = "1.0.38"
bstr = { version = "1.3.0", default-features = false, features = [
    "std",
    "unicode",
] }
winnow = { version = "0.6.0", features = ["simd"] }
itoa = "1.0.1"
serde = { version = "1.0.114", optional = true, default-features = false, features = [
    "derive",
] }

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
pretty_assertions = "1.0.0"
gix-testtools = { path = "../tests/tools" }
gix-hash = { path = "../gix-hash" }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
