[package]
name = "gix-prompt"
version = "0.7.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project for handling prompts in the terminal"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
gix-command = { version = "^0.2.9", path = "../gix-command" }
gix-config-value = { version = "^0.14.0", path = "../gix-config-value" }

thiserror = "1.0.32"
parking_lot = "0.12.1"

[target.'cfg(unix)'.dependencies]
rustix = { version = "0.38.4", features = ["termios"] }

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}
serial_test = { version = "2.0.0", default-features = false }
expectrl = "0.7.0"
