[package]
name = "gix-config"
version = "0.31.0"
repository = "https://github.com/Byron/gitoxide"
description = "A git-config file parser and editor from the gitoxide project"
license = "MIT OR Apache-2.0"
authors = ["Edward Shen <code@eddie.sh>"]
edition = "2021"
keywords = ["git-config", "git", "config", "gitoxide"]
categories = ["config", "parser-implementations"]
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-version = "1.65"
autotests = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-sec/serde", "gix-ref/serde", "gix-glob/serde", "gix-config-value/serde"]

[dependencies]
gix-features = { version = "^0.36.0", path = "../gix-features"}
gix-config-value = { version = "^0.14.0", path = "../gix-config-value" }
gix-path = { version = "^0.10.0", path = "../gix-path" }
gix-sec = { version = "^0.10.0", path = "../gix-sec" }
gix-ref = { version = "^0.38.0", path = "../gix-ref" }
gix-glob = { version = "^0.14.0", path = "../gix-glob" }

winnow = { version = "0.5.14", features = ["simd"] }
memchr = "2"
thiserror = "1.0.26"
unicode-bom = "2.0.2"
bstr = { version = "1.3.0", default-features = false, features = ["std"] }
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}
smallvec = "1.9.0"
once_cell = "1.14.0"

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "large_config_file"
harness = false
path = "./benches/large_config_file.rs"

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
rustdoc-args = ["--cfg", "docsrs"]
