[package]
name = "gix-odb"
version = "0.54.0"
repository = "https://github.com/Byron/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT OR Apache-2.0"
description = "Implements various git object databases"
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"
autotests = false

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde= ["dep:serde", "gix-hash/serde", "gix-object/serde", "gix-pack/serde"]

[dependencies]
gix-features = { version = "^0.36.0", path = "../gix-features", features = ["rustsha1", "walkdir", "zlib", "crc32" ] }
gix-hash = { version = "^0.13.1", path = "../gix-hash" }
gix-date = { version = "^0.8.0", path = "../gix-date" }
gix-path = { version = "^0.10.0", path = "../gix-path" }
gix-quote = { version = "^0.4.7", path = "../gix-quote" }
gix-object = { version = "^0.38.0", path = "../gix-object" }
gix-pack = { version = "^0.44.0", path = "../gix-pack", default-features = false }
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

tempfile = "3.1.0"
thiserror = "1.0.26"
parking_lot = { version = "0.12.0" }
arc-swap = "1.5.0"

document-features = { version = "0.2.0", optional = true }

#[dev-dependencies]
#gix-testtools = { path = "../tests/tools"}
#gix-actor = { path = "../gix-actor" }
#pretty_assertions = "1.0.0"
#filetime = "0.2.15"
#maplit = "1.0.2"
#crossbeam-channel = "0.5.6"

[package.metadata.docs.rs]
features = ["document-features", "serde"]
rustdoc-args = ["--cfg", "docsrs"]
