[package]
name = "gix-odb"
version = "0.50.1"
repository = "https://github.com/Byron/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT OR Apache-2.0"
description = "Implements various git object databases"
edition = "2021"
include = ["src/**/*", "LICENSE-*", "CHANGELOG.md"]
rust-version = "1.65"

[lib]
doctest = false

[features]
internal-testing-gix-features-parallel = ["gix-features/parallel"]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde= ["dep:serde", "gix-hash/serde", "gix-object/serde", "gix-pack/serde"]

[[test]]
name = "multi-threaded"
path = "tests/odb-multi-threaded.rs"
required-features = ["internal-testing-gix-features-parallel"]

[[test]]
name = "single-threaded"
path = "tests/odb-single-threaded.rs"
required-features = []

[dependencies]
gix-features = { version = "^0.32.1", path = "../gix-features", features = ["rustsha1", "walkdir", "zlib", "crc32" ] }
gix-hash = { version = "^0.11.4", path = "../gix-hash" }
gix-date = { version = "^0.7.1", path = "../gix-date" }
gix-path = { version = "^0.8.4", path = "../gix-path" }
gix-quote = { version = "^0.4.6", path = "../gix-quote" }
gix-object = { version = "^0.33.1", path = "../gix-object" }
gix-pack = { version = "^0.40.1", path = "../gix-pack" }
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

tempfile = "3.1.0"
thiserror = "1.0.26"
parking_lot = { version = "0.12.0" }
arc-swap = "1.5.0"

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}
gix-actor = { path = "../gix-actor" }
pretty_assertions = "1.0.0"
filetime = "0.2.15"
maplit = "1.0.2"
crossbeam-channel = "0.5.6"

[package.metadata.docs.rs]
features = ["document-features", "serde"]
rustdoc-args = ["--cfg", "docsrs"]
