[package]
name = "gix-odb"
version = "0.61.1"
repository = "https://github.com/Byron/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT OR Apache-2.0"
description = "Implements various git object databases"
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"
autotests = false

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-hash/serde", "gix-object/serde", "gix-pack/serde"]

[dependencies]
gix-features = { version = "^0.38.2", path = "../gix-features", features = ["rustsha1", "walkdir", "zlib", "crc32"] }
gix-hash = { version = "^0.14.2", path = "../gix-hash" }
gix-date = { version = "^0.8.7", path = "../gix-date" }
gix-path = { version = "^0.10.9", path = "../gix-path" }
gix-quote = { version = "^0.4.12", path = "../gix-quote" }
gix-object = { version = "^0.42.3", path = "../gix-object" }
gix-pack = { version = "^0.51.1", path = "../gix-pack", default-features = false }
gix-fs = { version = "^0.11.2", path = "../gix-fs" }
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }

tempfile = "3.10.0"
thiserror = "1.0.26"
parking_lot = { version = "0.12.0" }
arc-swap = "1.5.0"

document-features = { version = "0.2.0", optional = true }

[package.metadata.docs.rs]
features = ["document-features", "serde"]
