[package]
name = "git-refspec"
version = "0.0.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project for parsing and representing refspecs"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "CHANGELOG.md", "README.md"]

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-revision = { version = "^0.3.0", path = "../git-revision" }
git-validate = { version = "^0.5.4", path = "../git-validate" }
git-hash = { version = "^0.9.7", path = "../git-hash" }

bstr = { version = "0.2.13", default-features = false, features = ["std"]}
thiserror = "1.0.26"
smallvec = "1.9.0"

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
