[package]
name = "gix-negotiate"
version = "0.15.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing negotiation algorithms"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false
test = false

[dependencies]
gix-hash = { version = "^0.14.2", path = "../gix-hash" }
gix-object = { version = "^0.44.0", path = "../gix-object" }
gix-date = { version = "^0.9.0", path = "../gix-date" }
gix-commitgraph = { version = "^0.24.3", path = "../gix-commitgraph" }
gix-revwalk = { version = "^0.15.0", path = "../gix-revwalk" }
thiserror = "1.0.40"
smallvec = "1.10.0"
bitflags = "2"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-odb = { path = "../gix-odb" }
gix-ref = { path = "../gix-ref" }
