[package]
name = "gix-utils"
version = "0.1.5"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate with `gitoxide` utilities that don't need feature toggles"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
fastrand = "2.0.0"
