[package]
name = "gix-lock"
version = "11.0.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A git-style lock-file implementation"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-version = "1.65"

[lib]
doctest = false
test = true

[dependencies]
gix-utils = { version = "^0.1.5", default-features = false, path = "../gix-utils" }
gix-tempfile = { version = "^11.0.0", default-features = false, path = "../gix-tempfile" }
thiserror = "1.0.38"

[dev-dependencies]
tempfile = "3.2.0"
