[package]
name = "git-sec"
version = "0.3.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project providing a shared trust model"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "CHANGELOG.md"]

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde1 = [ "serde" ]

[dependencies]
serde = { version = "1.0.114", optional = true, default-features = false, features = ["std", "derive"] }
bitflags = "1.3.2"
thiserror = { version = "1.0.26", optional = true }

document-features = { version = "0.2.1", optional = true }

[target.'cfg(not(windows))'.dependencies]
libc = "0.2.123"

[target.'cfg(windows)'.dependencies]
git-path = { version = "^0.4.1", path = "../git-path" }
dirs = "4"
windows = { version = "0.37.0", features = [ "alloc",
    "Win32_Foundation",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
    "Win32_System_Memory",
    "Win32_System_Threading"
] }

[dev-dependencies]
tempfile = "3.3.0"

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
rustdoc-args = ["--cfg", "docsrs"]
