[package]
name = "git-worktree"
version = "0.0.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dedicated implementing everything around working trees and git excludes"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde1 = [ "serde", "bstr/serde1", "git-index/serde1", "git-hash/serde1", "git-object/serde1" ]

[dependencies]
git-index = { version = "^0.1.0", path = "../git-index" }
git-hash = { version = "^0.9.0", path = "../git-hash" }
git-object = { version = "^0.17.0", path = "../git-object" }
git-features = { version = "^0.19.1", path = "../git-features" }

serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

quick-error = "2.0.1"
bstr = { version = "0.2.13", default-features = false }

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
git-odb = { path = "../git-odb" }

walkdir = "2.3.2"
tempfile = "3.2.0"

[package.metadata.docs.rs]
features = ["document-features", "serde1"]
