[package]
name = "git-worktree"
version = "0.9.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dedicated implementing everything around working trees and git excludes"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "CHANGELOG.md"]

[lib]
doctest = false

[[test]]
name = "multi-threaded"
path = "tests/worktree-multi-threaded.rs"
required-features = ["internal-testing-git-features-parallel"]

[[test]]
name = "single-threaded"
path = "tests/worktree-single-threaded.rs"
required-features = ["internal-testing-to-avoid-being-run-by-cargo-test-all"]

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde1 = [ "serde", "bstr/serde", "git-index/serde1", "git-hash/serde1", "git-object/serde1" ]

internal-testing-git-features-parallel = ["git-features/parallel"]
internal-testing-to-avoid-being-run-by-cargo-test-all = []

[dependencies]
git-index = { version = "^0.9.1", path = "../git-index" }
git-hash = { version = "^0.10.1", path = "../git-hash" }
git-object = { version = "^0.23.0", path = "../git-object" }
git-glob = { version = "^0.5.0", path = "../git-glob" }
git-path = { version = "^0.6.0", path = "../git-path" }
git-attributes = { version = "^0.6.0", path = "../git-attributes" }
git-features = { version = "^0.24.1", path = "../git-features" }

serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

thiserror = "1.0.26"
bstr = { version = "1.0.1", default-features = false }

document-features = { version = "0.2.0", optional = true }
io-close = "0.3.7"

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
git-odb = { path = "../git-odb" }
symlink = "0.1.0"

walkdir = "2.3.2"
tempfile = "3.2.0"

[package.metadata.docs.rs]
features = ["document-features", "serde1"]
rustdoc-args = ["--cfg", "docsrs"]
