[package]
name = "gix-ignore"
version = "0.11.4"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing .gitignore files"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-glob/serde"]

[dependencies]
gix-glob = { version = "^0.16.5", path = "../gix-glob" }
gix-path = { version = "^0.10.10", path = "../gix-path" }
gix-trace = { version = "^0.1.8", path = "../gix-trace" }

bstr = { version = "1.3.0", default-features = false, features = ["std", "unicode"] }
unicode-bom.workspace = true
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }

document-features = { version = "0.2.1", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-fs = { path = "../gix-fs" }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
