[package]
name = "gix-submodule"
version = "0.1.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A WIP crate of the gitoxide project dealing git submodules"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
gix-refspec = { version = "^0.15.0", path = "../gix-refspec" }
gix-config = { version = "^0.27.0", path = "../gix-config" }
gix-path = { version = "^0.8.4", path = "../gix-path" }
gix-url = { version = "^0.21.1", path = "../gix-url" }

bstr = { version = "1.5.0", default-features = false }
thiserror = "1.0.44"

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}
gix-features = { path = "../gix-features", features = ["walkdir"] }

