[package]
name = "gix-credentials"
version = "0.24.5"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project to interact with git credentials helpers"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-sec/serde"]

[dependencies]
gix-sec = { version = "^0.10.8", path = "../gix-sec" }
gix-url = { version = "^0.27.5", path = "../gix-url" }
gix-path = { version = "^0.10.10", path = "../gix-path" }
gix-command = { version = "^0.3.9", path = "../gix-command" }
gix-config-value = { version = "^0.14.8", path = "../gix-config-value" }
gix-prompt = { version = "^0.8.7", path = "../gix-prompt" }
gix-trace = { version = "^0.1.8", path = "../gix-trace" }

thiserror = "1.0.32"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
bstr = { version = "1.3.0", default-features = false, features = ["std"] }



document-features = { version = "0.2.1", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-sec = { path = "../gix-sec" }
once_cell = "1.19.0"

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
