[package]
name = "gix-archive"
version = "0.2.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "implements archive generation from of a tree"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
thiserror = "1.0.26"
gix-worktree-stream = { version = "^0.2.0", path = "../gix-worktree-stream" }
