[package]
name = "gix-archive"
version = "0.2.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "implements archive generation from of a tree"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
thiserror = "1.0.26"
gix-features = { version = "^0.32.0", path = "../gix-features", features = ["progress"] }
gix-hash = { version = "^0.11.3", path = "../gix-hash" }
gix-object = { version = "^0.33.0", path = "../gix-object" }
gix-attributes = { version = "^0.15.0", path = "../gix-attributes" }
gix-filter = { version = "^0.1.0", path = "../gix-filter" }
