[package]
name = "gix-archive"
version = "0.2.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "archive generation from of a worktree stream"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[features]
default = ["tar"]

## Enable the `tar` archive format. It has support for all information, except for object ids.
tar = ["dep:tar", "dep:gix-path"]


[dependencies]
gix-worktree-stream = { version = "^0.2.0", path = "../gix-worktree-stream" }
gix-object = { version = "^0.33.0", path = "../gix-object" }
gix-path = { version = "^0.8.3", path = "../gix-path", optional = true }

thiserror = "1.0.26"
bstr = { version = "1.5.0", default-features = false }

tar = { version = "0.4.38", optional = true }

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}
gix-odb = { path = "../gix-odb"}
gix-worktree = { path = "../gix-worktree"}
gix-hash = { path = "../gix-hash"}
gix-attributes = { path = "../gix-attributes"}
gix-object = { path = "../gix-object"}
gix-filter = { path = "../gix-filter"}

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
rustdoc-args = ["--cfg", "docsrs"]
