[package]
name = "git-discover"
version = "0.1.1"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "Discover git repositories and check if a directory is a git repository"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "CHANGELOG.md"]

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-sec = { version = "^0.1.1", path = "../git-sec", features = ["thiserror"] }
git-path = { version = "^0.1.2", path = "../git-path" }
git-ref = { version = "^0.13.0", path = "../git-ref" }
git-hash = { version = "^0.9.4", path = "../git-hash" }

bstr = { version = "0.2.13", default-features = false, features = ["std", "unicode"] }
thiserror = "1.0.26"

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
is_ci = "1.1.1"

[target.'cfg(target_os = "macos")'.dev-dependencies]
defer = "0.1.0"
tempfile = "3.2.0"
