[package]
name = "gix-macros"
version = "0.1.0"
edition = "2021"
description = "Proc-macro utilities for gix"
authors = [
    "Jiahao XU <Jiahao_XU@outlook.com>",
    "Andre Bogus <bogusandre@gmail.com>",
    "Sebastian Thiel <sebastian.thiel@icloud.com>",
]
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"

[lib]
proc_macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "fold"] }
quote = "1.0"
proc-macro2 = "1.0"

[dev-dependencies]
trybuild = "1.0"
