[package]
name = "gix-traverse"
version = "0.29.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "CHANGELOG.md"]
rust-version = "1.65"
autotests = false

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.11.3", path = "../gix-hash" }
gix-object = { version = "^0.32.0", path = "../gix-object" }
gix-date = { version = "^0.7.0", path = "../gix-date" }
gix-hashtable = { version = "^0.2.3", path = "../gix-hashtable" }
gix-revwalk = { version = "^0.3.0", path = "../gix-revwalk" }
gix-commitgraph = { version = "^0.17.1", path = "../gix-commitgraph" }
smallvec = "1.10.0"
thiserror = "1.0.32"
