[package]
name = "gix-traverse"
version = "0.36.2"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"
autotests = false

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.14.1", path = "../gix-hash" }
gix-object = { version = "^0.40.1", path = "../gix-object" }
gix-date = { version = "^0.8.3", path = "../gix-date" }
gix-hashtable = { version = "^0.5.1", path = "../gix-hashtable" }
gix-revwalk = { version = "^0.11.1", path = "../gix-revwalk" }
gix-commitgraph = { version = "^0.23.2", path = "../gix-commitgraph" }
smallvec = "1.10.0"
thiserror = "1.0.32"
