[package]
name = "gix-glob"
version = "0.10.1"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A WIP crate of the gitoxide project dealing with pattern matching"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde= ["dep:serde", "bstr/serde", "bitflags/serde"]

[dependencies]
gix-path = { version = "^0.8.4", path = "../gix-path" }
gix-features = { version = "^0.32.1", path = "../gix-features" }
bstr = { version = "1.3.0", default-features = false, features = ["std"]}
bitflags = "2"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
rustdoc-args = ["--cfg", "docsrs"]
