[package]
name = "git-url"
version = "0.7.3"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project implementing parsing and serialization of git-url"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*", "CHANGELOG.md"]

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde1 = ["serde", "bstr/serde1"]

[dependencies]
git-features = { version = "^0.22.3", path = "../git-features" }
git-path = { version = "^0.4.2", path = "../git-path" }

serde = { version = "1.0.114", optional = true, default-features = false, features = ["std", "derive"]}
thiserror = "1.0.32"
url = "2.1.1"
bstr = { version = "0.2.13", default-features = false, features = ["std"] }
home = "0.5.3"

document-features = { version = "0.2.0", optional = true }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
rustdoc-args = ["--cfg", "docsrs"]
