[package]
name = "gix-mailmap"
version = "0.14.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project for parsing mailmap files"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde= ["dep:serde", "bstr/serde", "gix-actor/serde"]

[dependencies]
gix-actor = { version = "^0.22.0", path = "../gix-actor" }
gix-date = { version = "^0.6.0", path = "../gix-date" }
bstr = { version = "1.3.0", default-features = false, features = ["std", "unicode"]}
thiserror = "1.0.38"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

document-features = { version = "0.2.0", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
rustdoc-args = ["--cfg", "docsrs"]
