[package]
name = "gix-worktree"
version = "0.24.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A WIP crate of the gitoxide project dedicated implementing everything around working trees and git excludes"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "CHANGELOG.md"]
rust-version = "1.65"

[lib]
doctest = false

[[test]]
name = "multi-threaded"
path = "tests/worktree-multi-threaded.rs"
required-features = ["internal-testing-gix-features-parallel"]

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = [ "dep:serde", "bstr/serde", "gix-index/serde", "gix-hash/serde", "gix-object/serde", "gix-attributes/serde", "gix-ignore/serde" ]

internal-testing-gix-features-parallel = ["gix-features/parallel"]

[dependencies]
gix-index = { version = "^0.22.0", path = "../gix-index" }
gix-fs = { version = "^0.4.1", path = "../gix-fs" }
gix-hash = { version = "^0.11.4", path = "../gix-hash" }
gix-object = { version = "^0.34.0", path = "../gix-object" }
gix-glob = { version = "^0.10.2", path = "../gix-glob" }
gix-path = { version = "^0.8.4", path = "../gix-path" }
gix-attributes = { version = "^0.16.0", path = "../gix-attributes" }
gix-ignore = { version = "^0.5.1", path = "../gix-ignore" }
gix-features = { version = "^0.32.1", path = "../gix-features" }
gix-filter = { version = "^0.3.0", path = "../gix-filter" }

serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}

thiserror = "1.0.26"
filetime = "0.2.15"
bstr = { version = "1.3.0", default-features = false }

document-features = { version = "0.2.0", optional = true }
io-close = "0.3.7"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-odb = { path = "../gix-odb" }
symlink = "0.1.0"
once_cell = "1.18.0"

walkdir = "2.3.2"
tempfile = "3.2.0"

[package.metadata.docs.rs]
features = ["document-features", "serde"]
rustdoc-args = ["--cfg", "docsrs"]
