[package]
name = "gix-worktree"
version = "0.36.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project for shared worktree related types and utilities."
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"
autotests = false

[lib]
doctest = false

[features]
default = ["attributes"]
## Instantiate stacks that can access `.gitattributes` information.
attributes = ["dep:gix-attributes", "dep:gix-validate"]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde", "gix-index/serde", "gix-hash/serde", "gix-object/serde", "gix-attributes?/serde", "gix-ignore/serde"]

[dependencies]
gix-index = { version = "^0.35.0", path = "../gix-index" }
gix-fs = { version = "^0.11.3", path = "../gix-fs" }
gix-hash = { version = "^0.14.2", path = "../gix-hash" }
gix-object = { version = "^0.44.0", path = "../gix-object" }
gix-glob = { version = "^0.16.5", path = "../gix-glob" }
gix-path = { version = "^0.10.10", path = "../gix-path" }
gix-attributes = { version = "^0.22.5", path = "../gix-attributes", optional = true }
gix-validate = { version = "^0.9.0", path = "../gix-validate", optional = true }
gix-ignore = { version = "^0.11.4", path = "../gix-ignore" }
gix-features = { version = "^0.38.2", path = "../gix-features" }

serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
bstr = { version = "1.3.0", default-features = false }

document-features = { version = "0.2.0", optional = true }

[package.metadata.docs.rs]
features = ["document-features", "serde"]
