[package]
name = "gix-pack"
version = "0.38.0"
repository = "https://github.com/Byron/gitoxide"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT/Apache-2.0"
description = "Implements git packs and related data structures"
edition = "2021"
include = ["src/**/*", "LICENSE-*", "CHANGELOG.md"]
rust-version = "1.65"
autotests = false

[lib]
doctest = false

[features]

## Provide a fixed-size allocation-free LRU cache for packs. It's useful if caching is desired while keeping the memory footprint
## for the LRU-cache itself low.
pack-cache-lru-static = ["dep:uluru"]
## Provide a hash-map based LRU cache whose eviction is based a memory cap calculated from object data.
pack-cache-lru-dynamic = ["dep:clru"]
## If set, select algorithms may additionally use a full-object cache which is queried before the pack itself.
object-cache-dynamic = ["dep:clru"]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-object/serde"]
## Make it possible to compile to the `wasm32-unknown-unknown` target.
wasm = ["gix-diff/wasm"]

[dependencies]
gix-features = { version = "^0.31.0", path = "../gix-features", features = ["crc32", "rustsha1", "progress", "zlib"] }
gix-path = { version = "^0.8.2", path = "../gix-path" }
gix-hash = { version = "^0.11.3", path = "../gix-hash" }
gix-chunk = { version = "^0.4.3", path = "../gix-chunk" }
gix-object = { version = "^0.31.0", path = "../gix-object" }
gix-traverse = { version = "^0.28.0", path = "../gix-traverse" }
gix-diff = { version = "^0.31.0", path = "../gix-diff" }
gix-hashtable = { version = "^0.2.2", path = "../gix-hashtable" }

memmap2 = "0.7.0"
smallvec = "1.3.0"
parking_lot = { version = "0.12.0", default-features = false }
thiserror = "1.0.26"
uluru = { version = "3.0.0", optional = true }
clru = { version = "0.6.1", optional = true }

serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }
## If enabled, `cargo doc` will see feature documentation from this manifest.
document-features = { version = "0.2.0", optional = true }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
gix-tempfile = { version = "^7.0.0", default-features = false, path = "../gix-tempfile" }

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}

[package.metadata.docs.rs]
all-features = true
features = ["document-features", "pack-cache-lru-dynamic", "object-cache-dynamic", "serde"]
rustdoc-args = ["--cfg", "docsrs"]
