[package]
name = "gix-index"
version = "0.33.1"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A work-in-progress crate of the gitoxide project dedicated implementing the git index file"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-version = "1.65"
autotests = false


[lib]
doctest = false
test = true

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "smallvec/serde", "gix-hash/serde"]

[dependencies]
gix-features = { version = "^0.38.2", path = "../gix-features", features = [
    "rustsha1",
    "progress",
] }
gix-hash = { version = "^0.14.2", path = "../gix-hash" }
gix-bitmap = { version = "^0.2.11", path = "../gix-bitmap" }
gix-object = { version = "^0.42.3", path = "../gix-object" }
gix-validate = { version = "^0.8.5", path = "../gix-validate" }
gix-traverse = { version = "^0.39.2", path = "../gix-traverse" }
gix-lock = { version = "^14.0.0", path = "../gix-lock" }
gix-fs = { version = "^0.11.2", path = "../gix-fs" }
gix-utils = { version = "^0.1.12", path = "../gix-utils" }

hashbrown = "0.14.3"
fnv = "1.0.7"
thiserror = "1.0.32"
memmap2 = "0.9.0"
filetime = "0.2.15"
bstr = { version = "1.3.0", default-features = false }

serde = { version = "1.0.114", optional = true, default-features = false, features = [
    "derive",
] }
smallvec = "1.7.0"
itoa = "1.0.3"
bitflags = "2"

document-features = { version = "0.2.0", optional = true }

[target.'cfg(not(windows))'.dependencies]
rustix = { version = "0.38.20", default-features = false, features = [
    "std",
    "fs",
] }
libc = { version = "0.2.149" }

[package.metadata.docs.rs]
features = ["document-features", "serde"]
