[package]
name = "gix-filter"
version = "0.0.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project implementing git filters"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.11.3", path = "../gix-hash" }
gix-trace = { version = "^0.1.2", path = "../gix-trace" }
gix-object = { version = "^0.32.0", path = "../gix-object" }
gix-command = { version = "^0.2.6", path = "../gix-command" }
gix-quote = { version = "^0.4.5", path = "../gix-quote" }
gix-path = { version = "^0.8.3", path = "../gix-path" }
gix-packetline = { package = "gix-packetline-blocking", version = "^0.16.3", path = "../gix-packetline-blocking" }

encoding_rs = "0.8.32"
bstr = { version = "1.5.0", default-features = false, features = ["std"] }
thiserror = "1.0.38"


[dev-dependencies]
once_cell = "1.18.0"
gix-testtools = { path = "../tests/tools" }
