[package]
name = "gix-filter"
version = "0.7.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing git filters"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.13.2", path = "../gix-hash" }
gix-trace = { version = "^0.1.4", path = "../gix-trace" }
gix-object = { version = "^0.39.0", path = "../gix-object" }
gix-command = { version = "^0.3.0", path = "../gix-command" }
gix-quote = { version = "^0.4.8", path = "../gix-quote" }
gix-utils = { version = "^0.1.6", path = "../gix-utils" }
gix-path = { version = "^0.10.1", path = "../gix-path" }
gix-packetline = { package = "gix-packetline-blocking", version = "^0.17.0", path = "../gix-packetline-blocking" }
gix-attributes = { version = "^0.20.1", path = "../gix-attributes" }

encoding_rs = "0.8.32"
bstr = { version = "1.5.0", default-features = false, features = ["std"] }
thiserror = "1.0.38"
smallvec = "1.10.0"


[dev-dependencies]
once_cell = "1.18.0"
gix-testtools = { path = "../tests/tools" }
gix-worktree = { path = "../gix-worktree", default-features = false, features = ["attributes"] }
