[package]
name = "git-diff"
version = "0.8.2"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "Calculate differences between various git objects"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-hash = { version = "^0.5.0", path = "../git-hash" }
git-object = { version ="0.12.0", path = "../git-object" }
quick-error = "2.0.0"

[dev-dependencies]
git-odb = { path = "../git-odb" }
git-traverse = { path = "../git-traverse" }
git-testtools = { path = "../tests/tools" }
