[package]
name = "gix-discover"
version = "0.26.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "Discover git repositories and check if a directory is a git repository"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
gix-sec = { version = "^0.10.0", path = "../gix-sec" }
gix-path = { version = "^0.10.0", path = "../gix-path" }
gix-ref = { version = "^0.38.0", path = "../gix-ref" }
gix-hash = { version = "^0.13.1", path = "../gix-hash" }

bstr = { version = "1.3.0", default-features = false, features = ["std", "unicode"] }
thiserror = "1.0.26"

[target.'cfg(windows)'.dependencies]
dunce = "1.0.3"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
serial_test = { version = "2.0.0", default-features = false }
is_ci = "1.1.1"

[target.'cfg(target_os = "macos")'.dev-dependencies]
defer = "0.1.0"

[target.'cfg(any(unix, windows))'.dev-dependencies]
tempfile = "3.2.0"
