[package]
name = "gix-ref"
version = "0.47.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate to handle git references"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"
autotests = false

[lib]
doctest = false
test = true

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "gix-hash/serde", "gix-actor/serde", "gix-object/serde"]

[dependencies]
gix-features = { version = "^0.38.2", path = "../gix-features", features = ["walkdir"] }
gix-fs = { version = "^0.11.3", path = "../gix-fs" }
gix-path = { version = "^0.10.10", path = "../gix-path" }
gix-hash = { version = "^0.14.2", path = "../gix-hash" }
gix-object = { version = "^0.44.0", path = "../gix-object" }
gix-utils = { version = "^0.1.11", path = "../gix-utils" }
gix-validate = { version = "^0.9.0", path = "../gix-validate" }
gix-actor = { version = "^0.32.0", path = "../gix-actor" }
gix-lock = { version = "^14.0.0", path = "../gix-lock" }
gix-tempfile = { version = "^14.0.0", default-features = false, path = "../gix-tempfile" }

thiserror = "1.0.34"
winnow.workspace = true
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"] }

# packed refs
memmap2 = "0.9.0"

document-features = { version = "0.2.1", optional = true }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
gix-date = { version = "^0.9.0", path = "../gix-date" }

[package.metadata.docs.rs]
features = ["document-features", "serde"]
