[package]
name = "gix-validate"
version = "0.8.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "Validation functions for various kinds of names in git"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"

[lib]
doctest = false
test = true

[dependencies]
thiserror = "1.0.34"
bstr = { version = "1.3.0", default-features = false, features = ["std"] }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
