[package]
name = "git-prompt"
version = "0.3.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A crate of the gitoxide project for handling prompts in the terminal"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "README.md", "CHANGELOG.md"]

[lib]
doctest = false

[dependencies]
git-command = { version = "^0.2.0", path = "../git-command" }
git-config-value = { version = "^0.10.0", path = "../git-config-value" }

thiserror = "1.0.32"
parking_lot = "0.12.1"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.26.1", default-features = false, features = ["term"] }

[dev-dependencies]
git-testtools = { path = "../tests/tools"}
serial_test = "0.9.0"
expectrl = "0.5.2"
