[package]
name = "git-traverse"
version = "0.8.2"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git-hash = { version ="^0.6.0", path = "../git-hash" }
git-object = { version ="^0.14.0", path = "../git-object" }
quick-error = "2.0.0"

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
git-odb = { path = "../git-odb" }
