[package]
name = "git-traverse"
version = "0.16.4"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false

[dependencies]
git-hash = { version = "^0.9.8", path = "../git-hash" }
git-object = { version = "^0.20.3", path = "../git-object" }
thiserror = "1.0.32"
hash_hasher = "2.0.3"

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
git-odb = { path = "../git-odb" }
