[package]
name = "git-traverse"
version = "0.20.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*"]

[lib]
doctest = false

[dependencies]
git-hash = { version = "^0.10.1", path = "../git-hash" }
git-object = { version = "^0.24.0", path = "../git-object" }
git-hashtable = { version = "^0.1.0", path = "../git-hashtable" }
thiserror = "1.0.32"

[dev-dependencies]
git-testtools = { path = "../tests/tools" }
git-odb = { path = "../git-odb" }
