[package]
name = "gix-fs"
version = "0.9.1"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate providing file system specific utilities to `gitoxide`"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[features]
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde"]

[dependencies]
gix-features = { version = "^0.37.1", path = "../gix-features" }
gix-utils = { version = "^0.1.8", path = "../gix-utils" }
serde = { version = "1.0.114", optional = true, default-features = false, features = ["std", "derive"] }

[dev-dependencies]
tempfile = "3.5.0"
