[package]
name = "gix-command"
version = "0.3.3"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project handling internal git command execution"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"
include = ["src/lib.rs", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-trace = { version = "^0.1.7", path = "../gix-trace" }
gix-path = { version = "^0.10.4", path = "../gix-path" }

bstr = { version = "1.5.0", default-features = false, features = ["std"] }
shell-words = "1.0"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
