[package]
name = "gix-command"
version = "0.2.10"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project handling internal git command execution"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"
include = ["src/lib.rs", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
bstr = { version = "1.5.0", default-features = false, features = ["std"] }

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
