[package]
name = "gix-trace"
description = "A crate to provide minimal `tracing` support that can be turned off to zero cost"
repository = "https://github.com/Byron/gitoxide"
version = "0.1.3"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.65"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false
test = false

[features]

## Note that there is no default feature, as the application is supposed to opt-in via `gix-features` or using this crate directly.
default = []

## Implement `tracing` with `tracing-core`, which provides applications with valuable performance details if they opt-in to it.
##
## Note that this may have overhead as well, thus instrumentations should be used stategically, only providing coarse tracing by default and adding details
## only where needed while marking them with the appropriate level.
tracing = [ "dep:tracing-core" ]

## If enabled, detailed tracing is also emitted, which can greatly increase insights but at a cost.
tracing-detail = [ ]


[dependencies]
tracing-core = { version = "0.1.31", optional = true }

document-features = { version = "0.2.0", optional = true }

[package.metadata.docs.rs]
all-features = true
features = ["document-features"]
rustdoc-args = ["--cfg", "docsrs"]
