[package]
name = "gix-worktree-state"
version = "0.4.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing setting the worktree to a particular state"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"
autotests = false

[lib]
doctest = false

[dependencies]
gix-worktree = { version = "^0.27.0", path = "../gix-worktree", default-features = false, features = ["attributes"] }
gix-index = { version = "^0.26.0", path = "../gix-index" }
gix-fs = { version = "^0.8.0", path = "../gix-fs" }
gix-hash = { version = "^0.13.1", path = "../gix-hash" }
gix-object = { version = "^0.38.0", path = "../gix-object" }
gix-glob = { version = "^0.14.0", path = "../gix-glob" }
gix-path = { version = "^0.10.0", path = "../gix-path" }
gix-features = { version = "^0.36.0", path = "../gix-features" }
gix-filter = { version = "^0.6.0", path = "../gix-filter" }

io-close = "0.3.7"
thiserror = "1.0.26"
bstr = { version = "1.3.0", default-features = false }
