[package]
name = "gix-worktree-state"
version = "0.2.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project implementing setting the worktree to a particular state"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "CHANGELOG.md"]
rust-version = "1.65"
autotests = false

[lib]
doctest = false

[dependencies]
gix-worktree = { version = "^0.25.0", path = "../gix-worktree" }
gix-index = { version = "^0.23.1", path = "../gix-index" }
gix-fs = { version = "^0.5.0", path = "../gix-fs" }
gix-hash = { version = "^0.12.0", path = "../gix-hash" }
gix-object = { version = "^0.35.0", path = "../gix-object" }
gix-glob = { version = "^0.11.0", path = "../gix-glob" }
gix-path = { version = "^0.9.0", path = "../gix-path" }
gix-features = { version = "^0.33.0", path = "../gix-features" }
gix-filter = { version = "^0.3.0", path = "../gix-filter" }

io-close = "0.3.7"
thiserror = "1.0.26"
bstr = { version = "1.3.0", default-features = false }
