[package]
name = "git-protocol"
version = "0.9.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project for implementing git protocols"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2018"
include = ["src/**/*"]

[lib]
doctest = false

[features]
serde1 = ["serde", "bstr/serde1", "git-transport/serde1", "git-hash/serde1"]
blocking-client = ["git-transport/blocking-client", "maybe-async/is_sync"]
async-client = ["git-transport/async-client", "async-trait", "futures-io", "futures-lite"]

[[test]]
name = "blocking-client-protocol"
path = "tests/blocking-protocol.rs"
required-features = ["blocking-client"]

[[test]]
name = "async-client-protocol"
path = "tests/async-protocol.rs"
required-features = ["async-client"]

[dependencies]
git-features = { version = "^0.16.0", path = "../git-features", features = ["progress"] }
git-transport = { version ="0.10.0", path = "../git-transport" }
git-hash = { version = "^0.5.0", path = "../git-hash" }

quick-error = "2.0.0"
serde = { version = "1.0.114", optional = true, default-features = false, features = ["derive"]}
bstr = { version = "0.2.13", default-features = false, features = ["std"] }
nom = { version = "7", default-features = false, features = ["std"]}
btoi = "0.4.2"

# for async-client
async-trait = { version = "0.1.51", optional = true }
futures-io = { version = "0.3.16", optional = true }
futures-lite = { version  = "1.12.0", optional = true }
maybe-async = "0.2.6"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }
git-packetline = { path = "../git-packetline" ,version ="0.9.0"}
git-testtools = { path = "../tests/tools" }
