[package]
name = "gix-worktree-stream"
version = "0.15.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "generate a byte-stream from a git-tree"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"
include = ["src/**/*", "LICENSE-*"]

[lib]
doctest = false

[dependencies]
gix-features = { version = "^0.38.2", path = "../gix-features", features = ["progress", "io-pipe"] }
gix-hash = { version = "^0.14.2", path = "../gix-hash" }
gix-object = { version = "^0.44.0", path = "../gix-object" }
gix-attributes = { version = "^0.22.5", path = "../gix-attributes" }
gix-filter = { version = "^0.13.0", path = "../gix-filter" }
gix-traverse = { version = "^0.41.0", path = "../gix-traverse" }
gix-fs = { version = "^0.11.3", path = "../gix-fs" }
gix-path = { version = "^0.10.10", path = "../gix-path" }

thiserror = "1.0.26"
parking_lot = "0.12.1"

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}
gix-odb = { path = "../gix-odb"}
gix-worktree = { path = "../gix-worktree", default-features = false, features = ["attributes"]}
