[package]
name = "gix-bitmap"
version = "0.2.5"
repository = "https://github.com/Byron/gitoxide"
license = "MIT/Apache-2.0"
description = "A WIP crate of the gitoxide project dedicated implementing the standard git bitmap format"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
rust-version = "1.65"

[lib]
doctest = false
test = true

[dependencies]
thiserror = "1.0.38"

[dev-dependencies]
gix-testtools = { path = "../tests/tools"}
