[package]
name = "gix-packetline-blocking"
version = "0.16.6"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A duplicate of `gix-packetline` with the `blocking-io` feature pre-selected"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"

[lib]
doctest = false

[features]
#! By default, all IO related capabilities will be missing unless one of the following is chosen.
default = ["blocking-io"]

## If set, all IO will become blocking. The same types will be used preventing side-by-side usage of blocking and non-blocking IO.
blocking-io = []

#! ### Other
## Data structures implement `serde::Serialize` and `serde::Deserialize`.
serde = ["dep:serde", "bstr/serde"]

[dependencies]
gix-trace = { version = "^0.1.3", path = "../gix-trace" }

serde = { version = "1.0.114", optional = true, default-features = false, features = ["std", "derive"]}
thiserror = "1.0.34"
faster-hex = "0.8.0"
bstr = { version = "1.3.0", default-features = false, features = ["std"] }

document-features = { version = "0.2.0", optional = true }

[package.metadata.docs.rs]
features = ["document-features", "blocking-io", "serde"]
rustdoc-args = ["--cfg", "docsrs"]
