[package]
name = "gix-refspec"
version = "0.19.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project for parsing and representing refspecs"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*", "README.md"]
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
gix-revision = { version = "^0.23.0", path = "../gix-revision", default-features = false }
gix-validate = { version = "^0.8.0", path = "../gix-validate" }
gix-hash = { version = "^0.13.1", path = "../gix-hash" }

bstr = { version = "1.3.0", default-features = false, features = ["std"]}
thiserror = "1.0.26"
smallvec = "1.9.0"

[dev-dependencies]
gix-testtools = { path = "../tests/tools" }
