[package]
name = "gix-revwalk"
version = "0.13.2"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate providing utilities for walking the revision graph"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
gix-hash = { version = "^0.14.2", path = "../gix-hash" }
gix-object = { version = "^0.42.3", path = "../gix-object" }
gix-date = { version = "^0.8.7", path = "../gix-date" }
gix-hashtable = { version = "^0.5.2", path = "../gix-hashtable" }
gix-commitgraph = { version = "^0.24.3", path = "../gix-commitgraph" }

thiserror = "1.0.26"
smallvec = "1.10.0"
