[package]
name = "gix-path"
version = "0.10.0"
repository = "https://github.com/Byron/gitoxide"
license = "MIT OR Apache-2.0"
description = "A crate of the gitoxide project dealing paths and their conversions"
authors = ["Sebastian Thiel <sebastian.thiel@icloud.com>"]
edition = "2021"
include = ["src/**/*", "LICENSE-*"]
rust-version = "1.65"

[lib]
doctest = false

[dependencies]
gix-trace = { version = "^0.1.3", path = "../gix-trace" }
bstr = { version = "1.3.0", default-features = false, features = ["std"] }
thiserror = "1.0.26"
once_cell = "1.17.1"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
home = "0.5.4"

[dev-dependencies]
tempfile = "3.3.0"
